name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      GCP_CREDS: ${{ secrets.GCP_CREDS }}
      IMAGE_TAG: ${{ format('{0}-{1}', 'web-app', github.run_number) }}

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_TAG }}
    - name: Run container
      run: docker run -d -e GCP_CREDS="$GCP_CREDS" -p 8080:8080 ${{ env.IMAGE_TAG }}
    - name: Execute make test inside container
      run: docker exec -it ${{ env.IMAGE_TAG }} bash -c "make test"
