name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      GCP_CREDS: ${{ secrets.GCP_CREDS }}

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t web-app
    - name: Run container
      run: docker run --name app-container -d -e GCP_CREDS="$GCP_CREDS" -p 8080:8080 web-app
    - name: Execute make test inside container
      run: docker exec app-container bash -c "make test"
    - name: Stop
      run: docker stop app-container
    - name: Remove container
      run: docker rm app-container
    - name: Remove Image
      run: docker rmi -f web-app
      
